### ISSUE TITLE
Missing a fundamental element

### ISSUE THREAD

**Issue by haimamire** [Yocker64/git_test#1]
There's no neofetch in this repository. I hope it gets fixed.

**Comment by Yocker64** [comment]
Our team of software developers is always keen to hear your suggestions.
Unfortunately, adding "neofetch" to this project is out of the scope of the first release plans. That being said, we are more than glad to get feedback from our users so we are gonna take into consideration your suggestion dear user for future releases. With nothing left to say I wish you the best of the lucks on your coding journey dear fellow programmer. 

Best regards!

**Comment by Yocker64** [comment]
Update 20224-11-27 9:37 (UTC)
Missing a fundamental element issue addressed.
